<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class category_codesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $category_codes = [
            'Director',
            'General Manager',
            'PHMC Manager',
            'Lab Manager',
            'Site Manager',
            'Manager Engineer',
            'Project Manager',
            'Project Planning Engineering Manager',
            'Engineering Manager',
            'Contruction Manager',
            'Site Manager (HVAC)',
            'Project Operational Manager',
            'Sales Manager',
            'Quality Assurance Manager',
            'After Sales Technical Support and Assignment Site Manager',
            'Field Manager',
            'Plant Manager',
            'Commercial Manager',
            'Superintendent',
            'Supervisor',
            'Foreman',
            'Planner',
            'Project Control',
            'Civil Engineer',
            'Construction Engineer',
            'Commisioning Engineer',
            'Electrical Engineer',
            'Drafter Engineer',
            'Data Analyst Engineer',
            'Data Process Engineer',
            'Dumping & Project Engineer',
            'FMS Engineer',
            'Geotech Engineer',
            'MWM Engineer',
            'Camera Engineer',
            'Field Concrete Engineer',
            'Field Service Engineer',
            'Drill & Blast Engineer',
            'HRSG Engineer',
            'Marine Field Engineer',
            'Mud Engineer',
            'Power Plant Engineer',
            'Project Engineer',
            'Quality Engineer',
            'Second Engineer',
            'Service Engineer',
            'Mine Plan Engineer',
            'Steel Structure Engineer',
            'Technical Support Engineer',
            'Drafter',
            'Developer',
            'Graduate Engineer',
            'Analyst',
            'Specialist',
            'Inspector',
            'Medical Staff',
            'Quality Assurance',
            'Quality Control',
            'Surveyor',
            'Material Control',
            'Jr. Architect',
            'Trainer',
            'Geologist',
            'Auditor',
            'HSE',
            'Advisor',
            'Expeditor, Logistic',
            'Metallurgist',
            'Scheduler',
            'IT',
            'Banksman',
            'Welder',
            'Fitter',
            'Grinderman',
            'Rigger',
            'Scaffolder',
            'Painter',
            'Blaster',
            'Mechanic',
            'Electrician',
            'Maintenance',
            'Driller',
            'Fire Fighter',
            'Soil Technician',
            'Plumber',
            'Carpenter',
            'Rebarman',
            'Mooringman',
            'Cameraman',
            'Civil Crew',
            'Operator STP',
            'Operator Fuel',
            'Operator Shelter',
            'Operator Boom Truck',
            'Operator Chainsaw',
            'Operator HDPE',
            'Operator Wheel Loader',
            'Operator Solar PV',
            'Operator Service Equipment',
            'Operator Excavator',
            'Operator Mobile Crusher',
            'Operator Drill',
            'Operator Loader',
            'Operator Dozer',
            'Operator Telehandler',
            'Operator Forklift',
            'Operator Backhoe Loader',
            'Operator Crane',
            'Operator Batching Plant',
            'Operator Concrete Pump',
            'Operator Compactor',
            'Operator Bore Pile',
            'Operator Genset',
            'Operator Trailer',
            'Operator Winch',
            'Operator Hydrotest',
            'Operator Boom Lift',
            'Able Body',
            'Flagman',
            'Gardener',
            'Mason',
            'Spotter',
            'Building Tradesman',
            'Masinis',
            'Laundry',
            'Diswasher',
            'Signmaker',
            'Tyreman',
            'Ship Crew',
            'Boilermaker',
            'Nozzleman',
            'Asst. Concrete Pump',
            'Asst. Bus',
            'Asst. Surveyor',
            'Asst. Mechanic',
            'Asst. Rebarman',
            'Asst. Driller',
            'Asst. Logistic',
            'Ast Dispatcher',
            'Blast Crew',
            'Storeman',
            'Helper',
            'Cleaning Service',
            'Driver',
            'Admin',
            'Accounting',
            'Finance',
            'Human Resources',
            'Compliance Officer',
            'Procurement',
            'Document Control',
            'Reseptionist',
            'Timekeeper',
            'Broadcaster',
            'Cashier',
            'Chef',
            'Cook',
            'Security Officer',
            'Internship',
            'Supermarket Crew',
            'Religion Community',
            'Tenant Food Court Crew',
            'Cafe Crew',
            'Visitor',
        ];

        foreach ($category_codes as $cat_code) {
            DB::table('category_codes')->insert([
                'job_code' => $cat_code,
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }
    }
}
